export const serviceCategories = [
  'Plumber', 'Electrician', 'Carpenter', 'Painter', 'Mechanic', 'Auto Electrician',
  'Tailor', 'Fashion Designer', 'Barber', 'Hairdresser', 'Beautician', 'Nail Technician',
  'Cleaner', 'House Keeper', 'Security Guard', 'Bouncer', 'Driver', 'Chauffeur',
  'Chef', 'Caterer', 'Baker', 'Butcher', 'Fishmonger', 'Photographer', 'Videographer',
  'DJ', 'MC', 'Event Planner', 'Wedding Planner', 'Decorator', 'Florist',
  'Computer Repair', 'Phone Repair', 'Laptop Technician', 'Network Technician', 'IT Support',
  'Lawyer', 'Legal Consultant', 'Accountant', 'Bookkeeper', 'Tax Consultant', 'Auditor',
  'Nurse', 'Caregiver', 'Physiotherapist', 'Massage Therapist', 'Counselor', 'Psychologist',
  'Teacher', 'Tutor', 'Driving Instructor', 'Music Teacher', 'Dance Instructor', 'Art Teacher',
  'Welder', 'Metal Fabricator', 'Mason', 'Brick Layer', 'Roofer', 'Tiler',
  'Pool Cleaner', 'Pool Technician', 'Pest Control', 'Fumigator', 'Gardener', 'Landscaper',
  'Real Estate Agent', 'Property Manager', 'Surveyor', 'Architect', 'Interior Designer',
  'Farmer', 'Agricultural Consultant', 'Veterinarian', 'Animal Trainer', 'Pet Groomer',
  'Mobile Money Agent', 'Bank Agent', 'Insurance Agent', 'Microfinance Officer',
  'Graphic Designer', 'Web Designer', 'Web Developer', 'App Developer', 'Software Engineer',
  'Content Writer', 'Copywriter', 'Translator', 'Interpreter', 'Transcriptionist',
  'Social Media Manager', 'Digital Marketer', 'SEO Specialist', 'Email Marketer',
  'Watch Repair', 'Jewelry Repair', 'Shoe Repair', 'Shoe Shiner', 'Bag Repair',
  'Solar Installer', 'Solar Technician', 'Inverter Technician', 'Generator Technician',
  'Cyber Cafe Operator', 'Internet Cafe', 'Printing Services', 'Photocopying', 'Lamination',
  'Tour Guide', 'Travel Agent', 'Hotel Booking Agent', 'Safari Operator', 'Car Rental',
  'Gym Trainer', 'Personal Trainer', 'Yoga Instructor', 'Nutritionist', 'Dietitian',
  'Traditional Healer', 'Herbalist', 'Spiritual Healer', 'Fortune Teller',
  'Kiosk Vendor', 'Shopkeeper', 'Retail Store Owner', 'Supermarket Owner', 'Boutique Owner',
  'Gas Delivery', 'Water Delivery', 'Milk Delivery', 'Newspaper Delivery', 'Courier Service',
  'Excavator Operator', 'Bulldozer Operator', 'Crane Operator', 'Forklift Operator',
  'Truck Driver', 'Delivery Driver', 'Ride Share Driver', 'Taxi Driver', 'Bus Driver', 'Boda Boda Rider',
  'Car Wash', 'Auto Detailing', 'Window Tinting', 'Car Upholstery', 'Spare Parts Dealer',
  'Scrap Metal Dealer', 'Recycling Services', 'Waste Management', 'Garbage Collection',
  'Fire Safety Officer', 'First Aid Trainer', 'Safety Consultant', 'Security Systems Installer',
  'CCTV Installer', 'Alarm Technician', 'Locksmith', 'Safe Technician',
  'Furniture Maker', 'Furniture Repair', 'Upholsterer', 'Curtain Maker', 'Blind Installer',
  'Air Conditioner Repair', 'Fridge Repair', 'Washing Machine Repair', 'Microwave Repair',
  'TV Repair', 'Radio Repair', 'Speaker Repair', 'Electronics Repair',
  'Bicycle Repair', 'Motorcycle Repair', 'Motorcycle Mechanic', 'Spare Parts Seller',
  'Construction Worker', 'General Laborer', 'Mover', 'Packer', 'Warehouse Worker',
  'Sales Representative', 'Marketing Agent', 'Brand Ambassador', 'Promoter', 'Canvasser',
  'Debt Collector', 'Process Server', 'Private Investigator', 'Bodyguard',
  'Speech Therapist', 'Occupational Therapist', 'Special Needs Teacher', 'Sign Language Interpreter',
  'Braille Transcriber', 'Audio Describer', 'Disability Support Worker',
  'Childcare Provider', 'Babysitter', 'Nanny', 'Daycare Owner', 'Preschool Teacher',
  'Elderly Care', 'Home Care Worker', 'Hospice Worker', 'Palliative Care',
  'Funeral Director', 'Mortician', 'Grave Digger', 'Cemetery Caretaker',
  'Marriage Counselor', 'Family Therapist', 'Life Coach', 'Career Coach', 'Business Coach',
  'Public Speaker', 'Motivational Speaker', 'Trainer', 'Facilitator', 'Workshop Leader',
  'Researcher', 'Data Entry Clerk', 'Virtual Assistant', 'Personal Assistant', 'Secretary',
  'Receptionist', 'Call Center Agent', 'Customer Service Representative', 'Telemarketer',
  'Debt Counselor', 'Financial Advisor', 'Investment Advisor', 'Stock Broker', 'Forex Trader',
  'Insurance Broker', 'Mortgage Broker', 'Loan Officer', 'Credit Officer',
  'Human Resources Consultant', 'Recruiter', 'Headhunter', 'Career Consultant',
  'Environmental Consultant', 'Energy Auditor', 'Sustainability Consultant', 'Climate Advisor',
  'Sports Coach', 'Football Coach', 'Basketball Coach', 'Swimming Instructor', 'Tennis Coach',
  'Martial Arts Instructor', 'Boxing Coach', 'Wrestling Coach', 'Athletics Coach',
  'Chess Instructor', 'Board Game Tutor', 'Puzzle Maker', 'Game Developer',
  'Drone Operator', 'Drone Photographer', 'Aerial Surveyor', 'Drone Trainer',
  '3D Printer Technician', 'Laser Cutter Operator', 'CNC Machine Operator', 'Machinist',
  'Glass Blower', 'Potter', 'Ceramicist', 'Sculptor', 'Wood Carver', 'Stone Carver',
  'Embroiderer', 'Knitter', 'Crocheter', 'Quilter', 'Weaver', 'Basket Weaver',
  'Bead Maker', 'Jewelry Designer', 'Accessory Designer', 'Bag Designer', 'Shoe Designer',
  'Tattoo Artist', 'Piercing Artist', 'Body Modification Artist', 'Permanent Makeup Artist',
  'Makeup Artist', 'Bridal Makeup', 'Special Effects Makeup', 'Theatrical Makeup',
  'Hair Stylist', 'Wig Maker', 'Hair Extension Specialist', 'Braider', 'Dreadlock Technician',
  'Skin Care Specialist', 'Esthetician', 'Spa Therapist', 'Wellness Coach', 'Meditation Instructor',
  'Aromatherapist', 'Reflexologist', 'Acupuncturist', 'Chiropractor', 'Osteopath',
  'Blood Pressure Monitor', 'Diabetes Educator', 'HIV Counselor', 'Family Planning Counselor',
  'Midwife', 'Birth Doula', 'Postpartum Doula', 'Lactation Consultant', 'Infant Care Specialist',
  'Pet Sitter', 'Dog Walker', 'Animal Boarding', 'Pet Trainer', 'Animal Behaviorist',
  'Horse Trainer', 'Riding Instructor', 'Stable Manager', 'Farrier', 'Equine Therapist',
  'Poultry Farmer', 'Dairy Farmer', 'Fish Farmer', 'Beekeeper', 'Snail Farmer',
  'Compost Maker', 'Organic Fertilizer Producer', 'Seedling Producer', 'Horticulturist',
  'Irrigation Technician', 'Borehole Driller', 'Well Digger', 'Water Treatment Specialist',
  'Solar Water Heater Installer', 'Biogas Installer', 'Wind Turbine Technician',
  'Electric Vehicle Technician', 'Charging Station Installer', 'Battery Technician',
  'E-waste Recycler', 'Computer Assembler', 'Phone Assembler', 'Electronics Manufacturer',
  'TV Mounter', 'Mama Fua', 'Laundry Lady', 'DJ', 'MCs', 'Dancers', 'Event Organisers', 'Well Digger',
  'Dentist', 'Gynaecologist', 'Paediatrician', 'Optician', 'Dermatologist', 'Shylock',
];

export const businessCategories = [
  'Restaurant', 'Cafe', 'Fast Food', 'Hotel', 'Motel', 'Guest House', 'Lodging',
  'Supermarket', 'Grocery Store', 'Convenience Store', 'Kiosk', 'Retail Shop',
  'Boutique', 'Clothing Store', 'Shoe Store', 'Jewelry Store', 'Electronics Shop',
  'Phone Shop', 'Computer Shop', 'Furniture Store', 'Hardware Store', 'Building Materials',
  'Pharmacy', 'Chemist', 'Medical Clinic', 'Hospital', 'Dental Clinic', 'Optician',
  'Bookstore', 'Stationery Shop', 'Printing Press', 'Cyber Cafe', 'Internet Cafe',
  'Car Dealership', 'Car Parts Shop', 'Garage', 'Auto Repair Shop', 'Car Wash',
  'Gas Station', 'Petrol Station', 'Service Station', 'Parking Lot',
  'Beauty Salon', 'Barbershop', 'Spa', 'Massage Parlor', 'Nail Salon', 'Tattoo Parlor',
  'Gym', 'Fitness Center', 'Sports Club', 'Swimming Pool', 'Stadium',
  'School', 'College', 'University', 'Training Center', 'Driving School', 'Language School',
  'Bank', 'Microfinance', 'SACCO', 'Insurance Company', 'Investment Firm',
  'Real Estate Agency', 'Property Management', 'Construction Company', 'Architecture Firm',
  'Law Firm', 'Legal Services', 'Accounting Firm', 'Audit Firm', 'Consulting Firm',
  'IT Company', 'Software Company', 'Web Design Agency', 'Digital Marketing Agency',
  'Transport Company', 'Logistics Company', 'Courier Service', 'Delivery Service',
  'Tour Company', 'Travel Agency', 'Safari Operator', 'Hotel Booking', 'Car Rental',
  'Event Planning', 'Wedding Planning', 'Catering Service', 'Decoration Services',
  'Photography Studio', 'Video Production', 'Media Company', 'Advertising Agency',
  'Manufacturing', 'Factory', 'Processing Plant', 'Assembly Plant', 'Workshop',
  'Warehouse', 'Storage Facility', 'Cold Storage', 'Distribution Center',
  'Farm', 'Dairy Farm', 'Poultry Farm', 'Fish Farm', 'Greenhouse', 'Nursery',
  'Butchery', 'Meat Shop', 'Fish Market', 'Vegetable Market', 'Fruit Shop',
  'Bakery', 'Cake Shop', 'Pastry Shop', 'Ice Cream Parlor', 'Juice Bar',
  'Liquor Store', 'Wine Shop', 'Bar', 'Pub', 'Nightclub', 'Lounge',
  'Laundry', 'Dry Cleaner', 'Cleaning Services', 'Fumigation Services', 'Waste Management',
  'Security Company', 'Guard Services', 'Alarm Company', 'CCTV Installation',
  'Solar Company', 'Electrical Supplies', 'Plumbing Supplies', 'Hardware Store',
  'Paint Shop', 'Tile Shop', 'Flooring Store', 'Roofing Materials', 'Glass Shop',
  'Carpentry Shop', 'Woodworking', 'Furniture Workshop', 'Upholstery Shop',
  'Tailoring Shop', 'Embroidery', 'Screen Printing', 'Branding Services',
  'Daycare', 'Kindergarten', 'Primary School', 'Secondary School', 'Tuition Center',
  'Hospital', 'Clinic', 'Laboratory', 'Diagnostic Center', 'Pharmacy', 'Medical Supplies',
  'Veterinary Clinic', 'Pet Shop', 'Pet Grooming', 'Animal Feed Store',
  'Florist', 'Flower Shop', 'Garden Center', 'Plant Nursery', 'Landscaping Services',
  'Funeral Home', 'Mortuary', 'Cemetery Services', 'Cremation Services',
  'Church', 'Mosque', 'Temple', 'Religious Center', 'Community Center',
  'Cooperative', 'Farmers Market', 'Trading Center', 'Shopping Mall', 'Plaza',
  'Casino', 'Betting Shop', 'Lottery Shop', 'Gaming Center', 'Arcade',
  'Art Gallery', 'Museum', 'Cultural Center', 'Theater', 'Cinema', 'Concert Hall',
  'Library', 'Community Library', 'Mobile Library', 'Resource Center',
  'Radio Station', 'TV Station', 'Newspaper Office', 'Magazine Publisher',
  'Recycling Center', 'Scrap Yard', 'Junkyard', 'Second Hand Shop', 'Thrift Store',
  'Pawn Shop', 'Money Lender', 'Forex Bureau', 'Mobile Money Agent', 'ATM Services',
  'Courier Office', 'Post Office', 'Shipping Company', 'Freight Forwarder',
  'Employment Agency', 'Recruitment Firm', 'Manpower Services', 'Labor Supply',
  'Translation Office', 'Interpreter Services', 'Notary Public', 'Commissioner of Oaths',
  'Auction House', 'Estate Sale', 'Liquidation Services', 'Business Broker',
  'Franchise', 'Dealership', 'Distributor', 'Wholesaler', 'Importer', 'Exporter',
  'Mining Company', 'Quarry', 'Oil Company', 'Energy Company', 'Power Supplier',
  'Water Company', 'Sewage Services', 'Garbage Collection', 'Street Cleaning',
  'Road Construction', 'Bridge Construction', 'Building Contractor', 'Civil Engineering',
  'Interior Design Studio', 'Home Staging', 'Property Styling', 'Renovation Services',
  'Moving Company', 'Relocation Services', 'Storage Services', 'Packing Services',
  'Towing Service', 'Breakdown Service', 'Roadside Assistance', 'Emergency Services',
  'Fire Station', 'Police Station', 'Ambulance Service', 'Rescue Services',
  'NGO Office', 'Charity Organization', 'Community Organization', 'Social Services',
  'Embassy', 'Consulate', 'Government Office', 'Public Service', 'Municipal Office',
  'Court', 'Legal Aid', 'Probation Office', 'Correctional Facility',
  'Research Institute', 'Think Tank', 'Policy Center', 'Development Organization',
  'Tech Hub', 'Innovation Center', 'Startup Incubator', 'Co-working Space',
  'Call Center', 'BPO Office', 'Customer Support Center', 'Telemarketing Office',
  'Data Center', 'Server Farm', 'Cloud Services', 'Hosting Provider',
  'Cybersecurity Firm', 'IT Security', 'Network Security', 'Data Protection',
  'Drone Company', 'Aerial Photography', 'Surveying Company', 'Mapping Services',
  '3D Printing Service', 'Prototyping', 'Manufacturing Services', 'Fabrication',
  'Welding Shop', 'Metal Works', 'Iron Works', 'Steel Fabrication', 'Aluminum Works',
  'Plastic Factory', 'Rubber Products', 'Packaging Company', 'Label Printing',
  'Textile Mill', 'Garment Factory', 'Shoe Factory', 'Leather Goods', 'Bag Factory',
  'Food Processing', 'Beverage Company', 'Dairy Processing', 'Meat Processing',
  'Bottling Company', 'Canning Factory', 'Packaged Foods', 'Snack Factory',
  'Cosmetics Factory', 'Soap Factory', 'Detergent Factory', 'Chemical Products',
  'Pharmaceutical Company', 'Drug Manufacturer', 'Medical Equipment', 'Health Products',
  'Fertilizer Company', 'Agrochemicals', 'Seeds Company', 'Farm Inputs',
  'Construction Equipment', 'Heavy Machinery', 'Tools Shop', 'Equipment Rental',
  'Generator Sales', 'Solar Equipment', 'Inverter Sales', 'Battery Shop',
  'Air Conditioner Shop', 'Fridge Shop', 'Appliance Store', 'Electronics Store',
  'Bike Shop', 'Motorcycle Shop', 'Spare Parts', 'Accessories Shop', 'Tire Shop',
  'Fishing Supplies', 'Hunting Shop', 'Outdoor Gear', 'Sports Shop', 'Fitness Equipment',
  'Toy Shop', 'Baby Shop', 'Maternity Store', 'Kids Store', 'Children Products',
  'Gift Shop', 'Souvenir Shop', 'Craft Shop', 'Handicrafts', 'Art Supplies',
  'Musical Instruments', 'Music Store', 'Instrument Repair', 'Recording Studio',
  'Dance Studio', 'Yoga Studio', 'Meditation Center', 'Wellness Center', 'Health Spa',
  'Sauna', 'Steam Room', 'Jacuzzi', 'Hot Tub', 'Pool Services', 'Pool Supplies',
  'Air BnB', 'Event Tents', 'Event Sound',
];
